repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.13.0
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ ] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
