{{- if and .Values.frontend.enabled .Values.frontend.ingress.enabled }}
{{- $fullName := include "keep.fullname" . }}
{{- $frontendPort := .Values.frontend.service.port }}
{{- $websocketPort := .Values.websocket.service.port }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "keep.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/use-http2: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/server-snippets: |
      location /app/ {
        proxy_pass http://{{ $fullName }}-websocket:6001;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
    {{- with .Values.frontend.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- range .Values.frontend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.frontend.ingress.hosts }}
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- if and $.Values.websocket.enabled $websocketPort }}
        - path: /app
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-websocket
              port:
                number: {{ $websocketPort }}
        {{- end }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-frontend
              port:
                number: {{ $frontendPort }}
    {{- end }}
    {{- else }}
    - http:
        paths:
        {{- if and $.Values.websocket.enabled $websocketPort }}
        - path: /app
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-websocket
              port:
                number: {{ $websocketPort }}
        {{- end }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-frontend
              port:
                number: {{ $frontendPort }}
    {{- end }}
{{- end }}